import time
def p_seq():
    print("\n\t\t\t ", end = '')
    print(f"m", end ='')
    time.sleep(0.1)
    print(f"y", end ='')
    time.sleep(0.1)
    print(f".", end ='')
    time.sleep(0.1)
    print(f"p", end ='')
    time.sleep(0.1)
    print(f"y", end =' ')
    time.sleep(0.1)
    print(f"G", end ='')
    time.sleep(0.1)
    print(f"A", end ='')
    time.sleep(0.1)
    print(f"M", end ='')
    time.sleep(0.1)
    print(f"E", end ='')
    time.sleep(0.1)
    print(f"S", end =' ')
    time.sleep(0.1)
    print(f"P", end ='')
    time.sleep(0.1)
    print(f"R", end ='')
    time.sleep(0.1)
    print(f"E", end ='')
    time.sleep(0.1)
    print(f"S", end ='')
    time.sleep(0.1)
    print(f"E", end ='')
    time.sleep(0.1)
    print(f"N", end ='')
    time.sleep(0.1)
    print(f"T", end ='')
    time.sleep(0.1)
    print(f"S")
    time.sleep(0.8)
    print("\t\t\t       TIC")
    time.sleep(0.8)
    print("\t\t\t         TAC")
    time.sleep(0.8)
    print("\t\t\t           TOE")


